#!/usr/bin/env bash
# Install the pre-commit size guard hook into .git/hooks/pre-commit
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK="$SCRIPT_DIR/../.git/hooks/pre-commit"
GUARD="$SCRIPT_DIR/precommit_size_guard.sh"

if [ ! -d "$SCRIPT_DIR/../.git" ]; then
	echo "Not at repo root (run from inside repository)." >&2
	exit 1
fi

if [ ! -f "$GUARD" ]; then
	echo "Guard script missing: $GUARD" >&2
	exit 1
fi

cat > "$HOOK" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by lfs/install_precommit_hook.sh
bash lfs/precommit_size_guard.sh || exit 1
EOF
chmod +x "$HOOK"
echo "Installed pre-commit hook -> $HOOK"
echo "Set MAX_SIZE_MB env var before commit to override (default=5)."
